name: Build App and Upload Artifacts

on:
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize]

jobs:
  Build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: dist/grouper
            asset_name: grouper-linux-amd64
          - os: windows-latest
            file: dist/grouper.exe
            asset_name: grouper-windows-amd64.exe

    runs-on: ${{matrix.os}}
    name: Build ${{matrix.os}} binary
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run Pyinstaller
        run: |
          python ./build-scripts/build.py
      - name: Upload release artifacts
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.file }}
          tag: ${{ github.ref }}
          asset_name: ${{ matrix.asset_name}}
