name: Build App

on:
  workflow_dispatch:
  push:

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    name: Build ${{matrix.os}} binary
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run Pyinstaller
        run: |
          python ./build-scripts/build.py